name: Déploiement React sur GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    name: Construire et Tester
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Installation des dépendances
        run: npm ci

      - name: Exécution des tests
        run: npm test -- --run

      - name: Build de l'application
        run: npm run build
        env:
          VITE_API_URL: https://todo-back-pjbk.onrender.com

      - name: Uploader l'artefact de build
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"

  deploy:
    name: Déployer sur GitHub Pages
    needs: build-and-test
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Déployer sur GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4